# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Siyuan Blog
tagline:             'Write Some Code'
description:         'A Place To Log My Ideas'
url:                 'http://mzpz.me'
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Siyuan Ma
  url:               https://mzpz.me
  email:             smy20011@gmail.com

prose:
  rooturl: '_posts'
  siteurl: 'http://smy20011.github.io'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Compiler"
              value: "compiler"
            - name: "Android"
              value: "android"
